"""empty message

Revision ID: fb93f0dad83b
Revises: c62a0885dcf3
Create Date: 2024-03-04 15:21:52.229394

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fb93f0dad83b'
down_revision = 'c62a0885dcf3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('day_routines', schema=None) as batch_op:
        batch_op.drop_column('name')

    with op.batch_alter_table('routine_tasks', schema=None) as batch_op:
        batch_op.drop_column('name')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('routine_tasks', schema=None) as batch_op:
        batch_op.add_column(sa.Column('name', sa.VARCHAR(), nullable=True))

    with op.batch_alter_table('day_routines', schema=None) as batch_op:
        batch_op.add_column(sa.Column('name', sa.VARCHAR(), nullable=True))

    # ### end Alembic commands ###
